### ISSUE TITLE
InstRO Wiki

### ISSUE THREAD

**Issue by ciwainsky** [InstRO/InstRO#11]
We need an introduction to InstRO in the wiki.

**Comment by jplehr** [comment]
Should we have the website point to this wiki as well?
It is totally outdated right now.
http://www.sc.informatik.tu-darmstadt.de/res/instro_main/index.de.jsp

**Comment by jplehr** [comment]
I deleted the outdated website and wrote up a brief new one with a link to the github repository.

**Comment by ciwainsky** [comment]
Super,  danke

Von meinem Smartphone gesendet

---- Jan Patrick Lehr schrieb ----


I deleted the outdated website and wrote up a brief new one with a link to the github repository.
